version: '3.1'

services:
  rabbitmq:
    container_name: some-rabbit
    hostname: my-rabbit
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'  # Port for AMQP protocol
      - '15672:15672' # Port for Web Interface
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass123