version: '3.1'

services:
  frontend:
    container_name: frontend
    hostname: frontend
    build: frontend
    restart: always
    ports:
      - 80:80
      - 443:443
    #command: bash -c "tail -f /dev/null" # for debug only
  backend:
    container_name: backend
    hostname: backend
    build: backend
    restart: always
    environment:
      - SERVER_PORT=8080
      - SUBD_HOST=postgres
      - SUBD_PORT=5432
      - SUBD_DB=db
      - SUBD_USER=pguser
      - SUBD_PASS=pgPass
      - PASSWORD_HASH_SALT_OR_ROUNDS=15
      - JWT_SECRET=dfgergergergergreg
      - JWT_EXPIRES_IN=9h
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgPass
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data